#! /bin/bash

rm -rf site/.git
echo "unc-ch-aaup.org" > site/CNAME
git -C site init
git -C site add .
git -C site commit -m "Generated on $(date)"
git -C site remote add origin "git@github.com:unc-ch-aaup/unc-ch-aaup.github.io.git"
git -C site push -f origin main:site
